# \u914D\u7F6E\u6570\u636E\u5E93
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789
# \u914D\u7F6Emybatis-plus\u7684xml\u2F42\u4EF6\u626B\u63CF\u8DEF\u5F84
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
#shiro\u914D\u7F6E
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
# \u548C\u4EE3\u7801\u4E2D\u6307\u5B9A\u7684jwt\u524D\u7F00\u8981\u2F00\u81F4
zk:
  jwt:
    # \u52A0\u5BC6\u79D8\u94A5\uFF0C\u2F83\u2F30\u6307\u5B9A
    secret: f4e2e52034348f86b67cde581c0f9eb5
    # token\u6709\u6548\u65F6\u2ED3\u4E3A7\u5929\uFF0C\u5355\u4F4D\u662F\u79D2
    expire: 604800
    header: token
