# \u914D\u7F6E\u6570\u636E\u5E93
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456789
# \u914D\u7F6Emybatis-plus\u7684xml\u2F42\u4EF6\u626B\u63CF\u8DEF\u5F84
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
