server:
  port: 8081
spring:
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
zk:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization
